on:
  workflow_dispatch:
    inputs:
      reference-id:
        type: string
        required: true
      version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  propose-release:
    uses: DeterminateSystems/propose-release/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "write"
      pull-requests: write
    with:
      reference-id: ${{ inputs.reference-id }}
      version: ${{ inputs.version }}
      extra-commands-early: |
        nix develop -c ./tools/update-state.sh "v$VERSION"
        git diff || true
        git commit -m "Update the state.json for v$VERSION" ./tools/state.json
        nix develop -c ./tools/generate.sh
        git commit -m "Update README.md and action.yml for v$VERSION" README.md action.yml
        echo "Checking there is no remaining diff..."
        git diff --exit-code
